name = input ("what is your name : ")
age = input ("what is your age  : ")
claas = input ("in which class you are : ") 
colour = input ("what is your favourite colour : ")
favouritefood = input ("what is your favourite food : ")
favouritesport = input ("what is your favourite sport : ")
religion = input ("what is you religion : ")
cloth = input ("what is your favourite cloth : ")
siblings = input ("how many siblings do you have : ")
place = input ("what is your favourite place : ")
game = input ("what is your favourite mobile or online game : ")
job = input ("what job do you want to do : ")
freind =  input ("who is your best freind : ")
print ("your name is",name)
print ("your age is",age)
print ("you are in claas",claas)
print ("your favoourite colour is",colour)
print ("your favourite food is",favouritefood)
print ("your favourite sport is",favouritesport)
print ("your religion is",religion)
print ("your favourite cloth is",cloth)
print ("you have",siblings,str("siblings"))
print ("your favourite place is",place)
print ("your favourite moblie or online game is",game)
print ("your favourite job is",job)
print("your best freind is",freind)