age = input("what is your age")
claas = input("in which class you are") 
favouritefood = input("what is your favourite food")
favouritesport = input("what is your favourite sport")
print ("your age is",age)
print ("you are in claas",claas)
print ("your favourite food is",favouritefood)
print ("your favourite sport is",favouritesport)